### ISSUE TITLE
2M-NER论文代码

### ISSUE THREAD

**Issue by xiaoding06** [wangdsh/MMNERD#1]
您好我想问问这个代码是2M-NER论文的完整代码嘛

**Comment by wangdsh** [comment]
是的

**Comment by xiaoding06** [comment]
您好，想问问这个代码的pytorch版本python版本这些以及需要安装哪些库呢，在这代码上面没看到对应的requirement。

**Comment by wangdsh** [comment]
torch 2.x python 3.x
根据py文件import xxx，安装需要导入的库
